'use client';
import { useLiveQuery } from 'dexie-react-hooks';
import { Button } from '@/components/ui/button';
import { Modal } from '@/components/ui/modal';
import { getOpenConflicts, resolveConflictWithAction } from '@/lib/services/sync-conflict-service';
export function ConflictResolverModal({ userId }: { userId?: string }) {
  const conflicts = useLiveQuery(() => getOpenConflicts(), [], []); const open = conflicts.length > 0;
  return <Modal open={open} title="Some changes need your review" description="This account was used on another device or browser, and some items changed in both places. Choose how to resolve each conflict." onClose={() => undefined}><div className="space-y-4"><p className="text-sm text-slate-600">We will not silently overwrite business data. Review each difference, then choose which version to keep.</p>{conflicts.map(c=><div key={c.id} className="rounded-2xl border border-amber-200 bg-amber-50/60 p-4"><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-semibold text-slate-900 capitalize">{c.entity} conflict</p><p className="mt-1 text-xs text-slate-600">{c.conflictType.replaceAll('_',' ')} · {c.severity}</p></div><span className="rounded-full bg-white px-2 py-1 text-xs font-medium text-amber-700 ring-1 ring-amber-200">Needs review</span></div><div className="mt-3 grid gap-3 md:grid-cols-2"><pre className="max-h-40 overflow-auto rounded-xl bg-white p-3 text-xs text-slate-700 ring-1 ring-slate-200">{JSON.stringify(c.cloudRecord,null,2)}</pre><pre className="max-h-40 overflow-auto rounded-xl bg-white p-3 text-xs text-slate-700 ring-1 ring-slate-200">{JSON.stringify(c.localRecord,null,2)}</pre></div><div className="mt-4 flex flex-wrap justify-end gap-2"><Button type="button" variant="secondary" size="sm" onClick={()=>void resolveConflictWithAction(c.id,'keep_cloud',userId)}>Keep cloud</Button><Button type="button" variant="secondary" size="sm" onClick={()=>void resolveConflictWithAction(c.id,'keep_local',userId)}>Keep this device</Button><Button type="button" size="sm" onClick={()=>void resolveConflictWithAction(c.id,'manual',userId)}>Mark reviewed</Button></div></div>)}</div></Modal>;
}
